### ISSUE TITLE
Error whenever I try to generate a heatmap

### ISSUE THREAD

**Issue by elbamos** [toriato/stable-diffusion-webui-daam#13]
I see this error each time I try to generate a heatmap:

```
Error running process_batch: /home/me/projects/stable-diffusion-webui/extensions/stable-diffusion-webui-daam/scripts/daam_script.py
Traceback (most recent call last):
  File "/home/me/projects/stable-diffusion-webui/modules/scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "/home/me/projects/stable-diffusion-webui/extensions/stable-diffusion-webui-daam/scripts/daam_script.py", line 145, in process_batch
    prompt_analyzer = utils.PromptAnalyzer(embedder, styled_prompt)
  File "/home/me/projects/stable-diffusion-webui/extensions/stable-diffusion-webui-daam/scripts/daam/utils.py", line 274, in __init__
  File "/home/me/projects/stable-diffusion-webui/extensions/stable-diffusion-webui-daam/scripts/daam/utils.py", line 290, in tokenize_line
    def create(self, text : str):
TypeError: tokenize_line() takes 2 positional arguments but 4 were given
```

**Comment by rockerBOO** [comment]
What version of the webui? `git rev-parse HEAD` I had this error as well, but I forgot what I changed... Not a code change but maybe python modules or the webui updated (im on the latest and both work without code changes)

**Comment by Bing-su** [comment]
Modifying `tokenize_line` made it incompatible with old versions of webui. Please use the latest version of webui...
