### ISSUE TITLE
TypeError: FrozenCLIPEmbedderWithCustomWordsBase.tokenize_line() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by Gamekiller48** [toriato/stable-diffusion-webui-daam#8]
When trying to run this script, I receive the following error message:

```
Error running process_batch: E:\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "E:\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py", line 145, in process_batch
    prompt_analyzer = utils.PromptAnalyzer(embedder, styled_prompt)
  File "E:\stable-diffusion-webui\extensions\stable-diffusion-webui-daam_kousw\scripts\daam\utils.py", line 274, in __init__
  File "E:\stable-diffusion-webui\extensions\stable-diffusion-webui-daam_kousw\scripts\daam\utils.py", line 290, in tokenize_line
TypeError: FrozenCLIPEmbedderWithCustomWordsBase.tokenize_line() takes 2 positional arguments but 4 were given

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 10.48it/s]
Error running postprocess: E:\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.pyit/s]
Traceback (most recent call last):
  File "E:\stable-diffusion-webui\modules\scripts.py", line 404, in postprocess
    script.postprocess(p, processed, *script_args)
  File "E:\stable-diffusion-webui\extensions\stable-diffusion-webui-daam\scripts\daam_script.py", line 189, in postprocess
    for trace in self.tracers:
TypeError: 'NoneType' object is not iterable
```

people using the script this repo was forked from seem to have a smiliar problem: https://github.com/kousw/stable-diffusion-webui-daam/issues/25

**Comment by Gamekiller48** [comment]
local cache issue, issue is already fixed as of https://github.com/toriato/stable-diffusion-webui-daam/commit/9fe79da15a5ee2a91c27c090c182289f62ef8ef4
